# Generated by Django 4.2.27 on 2025-12-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_coursematerial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
