# Generated by Django 4.2.27 on 2025-12-20 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_coursematerial_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('idle', 'Idle'), ('working', 'Working'), ('paused', 'Paused'), ('break_distracted', 'Break Distracted')], default='idle', max_length=20)),
                ('current_cycle_start_time', models.DateTimeField(blank=True, null=True)),
                ('last_distraction_time', models.DateTimeField(blank=True, null=True)),
                ('work_duration_minutes', models.IntegerField(default=5)),
                ('pause_duration_minutes', models.IntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_pomodoro_sessions', to='api.classsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_pomodoro_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'class_session')},
            },
        ),
    ]
