# Generated by Django 4.2.27 on 2025-12-20 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pomodorosession'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pomodorosession',
            old_name='last_distraction_time',
            new_name='distraction_start_time',
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='current_cycle_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='last_recorded_distraction_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='total_distraction_duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='was_break_distracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='work_elapsed_time_on_pause',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
