# Generated by Django 4.2.27 on 2025-12-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_last_distraction_time_pomodorosession_distraction_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attentionrecord',
            name='raw_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
