# Generated by Django 4.2.27 on 2026-02-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_quiz_studentquizattempt_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursematerial',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de YouTube, Vimeo u otro servicio', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course_materials/'),
        ),
        migrations.AlterField(
            model_name='coursematerial',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('video', 'Video'), ('link', 'Enlace de Video'), ('other', 'Otro')], default='other', max_length=20),
        ),
    ]
