# Generated by Django 4.2.27 on 2026-02-13 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_coursematerial_video_url_alter_coursematerial_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PomodoroConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_work_duration', models.IntegerField(default=5, help_text='Duración inicial del período de trabajo (min)')),
                ('short_break_duration', models.IntegerField(default=2, help_text='Duración del descanso corto (min)')),
                ('long_break_duration', models.IntegerField(default=5, help_text='Duración del descanso largo (min)')),
                ('attention_threshold', models.IntegerField(default=85, help_text='Porcentaje mínimo de atención para ganar extensión (%)')),
                ('time_extension', models.IntegerField(default=3, help_text='Minutos adicionales por buena atención (min)')),
                ('max_work_duration', models.IntegerField(default=20, help_text='Duración máxima del período de trabajo (min)')),
                ('cycles_before_reset', models.IntegerField(default=4, help_text='Ciclos antes de resetear a duración inicial')),
                ('distraction_tolerance_seconds', models.IntegerField(default=30, help_text='Segundos de tolerancia para distracciones en pausa')),
                ('low_attention_threshold', models.IntegerField(default=50, help_text='Umbral de atención baja que pausa el tiempo (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoro_config', to='api.course')),
            ],
            options={
                'verbose_name': 'Configuración Pomodoro',
                'verbose_name_plural': 'Configuraciones Pomodoro',
            },
        ),
    ]
